In [1]:
import pandas as pd
import numpy as np

In [2]:
df =pd.read_csv('/home/prawin/Documents/processed_cleveland_data.csv')
df.tail()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
298,45,1,1,110,264,0,0,132,0,1.2,2,0.0,7.0,1
299,68,1,4,144,193,1,0,141,0,3.4,2,2.0,7.0,2
300,57,1,4,130,131,0,0,115,1,1.2,2,1.0,7.0,3
301,57,0,2,130,236,0,2,174,0,0.0,2,1.0,3.0,1
302,38,1,3,138,175,0,0,173,0,0.0,1,NaN,3.0,0

In [3]:
df['ca'].fillna(df['ca'].mean(),inplace=True)
df.tail()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
298,45,1,1,110,264,0,0,132,0,1.2,2,0.000000,7.0,1
299,68,1,4,144,193,1,0,141,0,3.4,2,2.000000,7.0,2
300,57,1,4,130,131,0,0,115,1,1.2,2,1.000000,7.0,3
301,57,0,2,130,236,0,2,174,0,0.0,2,1.000000,3.0,1
302,38,1,3,138,175,0,0,173,0,0.0,1,0.672241,3.0,0

In [4]:
df['thal'].fillna(df['thal'].mean(),inplace=True)
df.tail()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
298,45,1,1,110,264,0,0,132,0,1.2,2,0.000000,7.0,1
299,68,1,4,144,193,1,0,141,0,3.4,2,2.000000,7.0,2
300,57,1,4,130,131,0,0,115,1,1.2,2,1.000000,7.0,3
301,57,0,2,130,236,0,2,174,0,0.0,2,1.000000,3.0,1
302,38,1,3,138,175,0,0,173,0,0.0,1,0.672241,3.0,0

In [5]:
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,63,1,1,145,233,1,2,150,0,2.3,3,0.000000,6.0,0
1,67,1,4,160,286,0,2,108,1,1.5,2,3.000000,3.0,2
2,67,1,4,120,229,0,2,129,1,2.6,2,2.000000,7.0,1
3,37,1,3,130,250,0,0,187,0,3.5,3,0.000000,3.0,0
4,41,0,2,130,204,0,2,172,0,1.4,1,0.000000,3.0,0
5,56,1,2,120,236,0,0,178,0,0.8,1,0.000000,3.0,0
6,62,0,4,140,268,0,2,160,0,3.6,3,2.000000,3.0,3
7,57,0,4,120,354,0,0,163,1,0.6,1,0.000000,3.0,0
8,63,1,4,130,254,0,2,147,0,1.4,2,1.000000,7.0,2
9,53,1,4,140,203,1,2,155,1,3.1,3,0.000000,7.0,1
10,57,1,4,140,192,0,0,148,0,0.4,2,0.000000,6.0,0
11,56,0,2,140,294,0,2,153,0,1.3,2,0.000000,3.0,0
12,56,1,3,130,256,1,2,142,1,0.6,2,1.000000,6.0,2
13,44,1,2,120,263,0,0,173,0,0.0,1,0.000000,7.0,0
14,52,1,3,172,199,1,0,162,0,0.5,1,0.000000,7.0,0
15,57,1,3,150,168,0,0,174,0,1.6,1,0.000000,3.0,0
16,48,1,2,110,229,0,0,168,0,1.0,3,0.000000,7.0,1
17,54,1,4,140,239,0,0,160,0,1.2,1,0.000000,3.0,0
18,48,0,3,130,275,0,0,139,0,0.2,1,0.000000,3.0,0
19,49,1,2,130,266,0,0,171,0,0.6,1,0.000000,3.0,0
20,64,1,1,110,211,0,2,144,1,1.8,2,0.000000,3.0,0
21,58,0,1,150,283,1,2,162,0,1.0,1,0.000000,3.0,0
22,58,1,2,120,284,0,2,160,0,1.8,2,0.000000,3.0,1
23,58,1,3,132,224,0,2,173,0,3.2,1,2.000000,7.0,3
24,60,1,4,130,206,0,2,132,1,2.4,2,2.000000,7.0,4
25,50,0,3,120,219,0,0,158,0,1.6,2,0.000000,3.0,0
26,58,0,3,120,340,0,0,172,0,0.0,1,0.000000,3.0,0
27,66,0,1,150,226,0,0,114,0,2.6,3,0.000000,3.0,0
28,43,1,4,150,247,0,0,171,0,1.5,1,0.000000,3.0,0
29,40,1,4,110,167,0,2,114,1,2.0,2,0.000000,7.0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
273,71,0,4,112,149,0,0,125,0,1.6,2,0.000000,3.0,0
274,59,1,1,134,204,0,0,162,0,0.8,1,2.000000,3.0,1
275,64,1,1,170,227,0,2,155,0,0.6,2,0.000000,7.0,0
276,66,0,3,146,278,0,2,152,0,0.0,2,1.000000,3.0,0
277,39,0,3,138,220,0,0,152,0,0.0,2,0.000000,3.0,0
278,57,1,2,154,232,0,2,164,0,0.0,1,1.000000,3.0,1
279,58,0,4,130,197,0,0,131,0,0.6,2,0.000000,3.0,0
280,57,1,4,110,335,0,0,143,1,3.0,2,1.000000,7.0,2
281,47,1,3,130,253,0,0,179,0,0.0,1,0.000000,3.0,0
282,55,0,4,128,205,0,1,130,1,2.0,2,1.000000,7.0,3
283,35,1,2,122,192,0,0,174,0,0.0,1,0.000000,3.0,0
284,61,1,4,148,203,0,0,161,0,0.0,1,1.000000,7.0,2
285,58,1,4,114,318,0,1,140,0,4.4,3,3.000000,6.0,4
286,58,0,4,170,225,1,2,146,1,2.8,2,2.000000,6.0,2
287,58,1,2,125,220,0,0,144,0,0.4,2,0.672241,7.0,0
288,56,1,2,130,221,0,2,163,0,0.0,1,0.000000,7.0,0
289,56,1,2,120,240,0,0,169,0,0.0,3,0.000000,3.0,0
290,67,1,3,152,212,0,2,150,0,0.8,2,0.000000,7.0,1
291,55,0,2,132,342,0,0,166,0,1.2,1,0.000000,3.0,0
292,44,1,4,120,169,0,0,144,1,2.8,3,0.000000,6.0,2
293,63,1,4,140,187,0,2,144,1,4.0,1,2.000000,7.0,2
294,63,0,4,124,197,0,0,136,1,0.0,2,0.000000,3.0,1
295,41,1,2,120,157,0,0,182,0,0.0,1,0.000000,3.0,0
296,59,1,4,164,176,1,2,90,0,1.0,2,2.000000,6.0,3
297,57,0,4,140,241,0,0,123,1,0.2,2,0.000000,7.0,1
298,45,1,1,110,264,0,0,132,0,1.2,2,0.000000,7.0,1
299,68,1,4,144,193,1,0,141,0,3.4,2,2.000000,7.0,2
300,57,1,4,130,131,0,0,115,1,1.2,2,1.000000,7.0,3
301,57,0,2,130,236,0,2,174,0,0.0,2,1.000000,3.0,1
302,38,1,3,138,175,0,0,173,0,0.0,1,0.672241,3.0,0